name:                ytaudio
version:             0.1.0.0
github:              "githubuser/ytaudio"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ytaudio#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -fhide-source-paths
- -Wnoncanonical-monad-instances
- -Werror=incomplete-record-updates
- -Werror=incomplete-patterns
- -Werror=incomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wmissing-deriving-strategies
- -Wunused-packages
- -Werror=missing-fields
- -Werror=missing-methods
- -Wpartial-fields
- -Wredundant-constraints
- -Werror=empty-enumerations
- -Werror=missing-home-modules

default-extensions:
- BangPatterns
- BinaryLiterals
- DeriveGeneric
- DerivingStrategies
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications
# most of the list is copied from summoner
# https://github.com/kowainik/summoner/blob/main/summoner-cli/examples/stack-full/stack-full.cabal

library:
  source-dirs: src
  dependencies:
  - servant-server
  - text
  - wai
  - warp

executables:
  ytaudio:
    main:                Main.hs
    source-dirs:         program
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ytaudio

tests:
  ytaudio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ytaudio
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
